server:
  port: 8080

spring:
  datasource:
    username: root
    password: rishabh@123
    url: jdbc:mysql://localhost:3306/learncodedb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

